// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wCjPd4F8Exw4rGYU6oNU5VLQ91RUpNI',
    appId: '1:779263854703:web:afbd727839a05cede6e59a',
    messagingSenderId: '779263854703',
    projectId: 'smartfarm-6f510',
    authDomain: 'smartfarm-6f510.firebaseapp.com',
    storageBucket: 'smartfarm-6f510.firebasestorage.app',
    measurementId: 'G-6QB525KH0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmJgOlXirjP01QAEb99OWlWfvf3iOpCA',
    appId: '1:779263854703:android:7e16844b628d7b4be6e59a',
    messagingSenderId: '779263854703',
    projectId: 'smartfarm-6f510',
    storageBucket: 'smartfarm-6f510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhybY-cs_giIP_pEAObjTl-r0Y1p58kR0',
    appId: '1:779263854703:ios:548a90920e9d3766e6e59a',
    messagingSenderId: '779263854703',
    projectId: 'smartfarm-6f510',
    storageBucket: 'smartfarm-6f510.firebasestorage.app',
    iosBundleId: 'com.example.smartfarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhybY-cs_giIP_pEAObjTl-r0Y1p58kR0',
    appId: '1:779263854703:ios:548a90920e9d3766e6e59a',
    messagingSenderId: '779263854703',
    projectId: 'smartfarm-6f510',
    storageBucket: 'smartfarm-6f510.firebasestorage.app',
    iosBundleId: 'com.example.smartfarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_wCjPd4F8Exw4rGYU6oNU5VLQ91RUpNI',
    appId: '1:779263854703:web:afbd727839a05cede6e59a',
    messagingSenderId: '779263854703',
    projectId: 'smartfarm-6f510',
    authDomain: 'smartfarm-6f510.firebaseapp.com',
    storageBucket: 'smartfarm-6f510.firebasestorage.app',
    measurementId: 'G-6QB525KH0S',
  );

}